### ISSUE TITLE
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

### ISSUE THREAD

**Issue by spartucus** [echohive42/AI-reads-books-page-by-page#1]
Nice project!

I tried out with some error:
```shell
 % python read_books.py

📚 PDF Book Analysis Tool 📚
---------------------------
1. Place your PDF in the same directory as this script
2. Update PDF_NAME constant with your PDF filename
3. The script will:
   - Process the book page by page
   - Extract and save knowledge points
   - Generate interval summaries (if enabled)
   - Create a final comprehensive analysis

Configuration options:
- ANALYSIS_INTERVAL: Set to None to skip interval analyses, or a number for analysis every N pages
- TEST_PAGES: Set to None to process entire book, or a number for partial processing

Press Enter to continue or Ctrl+C to exit...


📄 Copied PDF to analysis directory: book_analysis/pdfs/ethStark.pdf
Traceback (most recent call last):
  File "/Users/bob/work/research/AI-reads-books-page-by-page/read_books.py", line 252, in <module>
    main()
    ~~~~^^
  File "/Users/bob/work/research/AI-reads-books-page-by-page/read_books.py", line 218, in main
    client = OpenAI()
  File "/Users/bob/work/research/AI-reads-books-page-by-page/venv/lib/python3.13/site-packages/openai/_client.py", line 110, in __init__
    raise OpenAIError(
        "The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable"
    )
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

Python 3.13.1

**Comment by hxbbing** [comment]
You can modify line 218 of the read_books.py file as:
`client = OpenAI(base_url="https://xxx", api_key="Your api_key")`
